version: 2
updates:
  - package-ecosystem: pip
    directory: /src
    schedule:
      interval: weekly
    groups:
      production:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      dev:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
